### ISSUE TITLE
Log  arguments along with query

### ISSUE THREAD

**Issue by JesusTheHun** [spring-projects/spring-data-couchbase#1311]
I expect this log level to display all queries that are executed :
```yml
logging:
    level:
        org.springframework.data.couchbase.repository.query: TRACE
```

The closest we get is with `org/springframework/data/couchbase/repository/query/StringBasedCouchbaseQuery.java` :

```java
		if (LOG.isDebugEnabled()) {
			LOG.debug("Created query " + query.export());
		}
```

But `query.export()` returns an empty string.

Expected output : the query itself + the parameters used for that execution.
